# fly.toml app configuration file generated for yt-dlp-server-iebqfa on 2025-07-01T06:49:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yt-dlp-server-iebqfa'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
